language: bash
sudo: required
dist: xenial
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_90df736c1e20_key -iv $encrypted_90df736c1e20_iv -in gantry.cfg.enc -out gantry.cfg -d
- docker build -t nlnetlabs/gantry .
script:
- >
  ./gantry --version
  ./gantry deploy --region nyc1 routinator vr-sros:16.0.R6 vr-vmx:18.2R1.9 && \
  ./gantry status && \
  ./gantry --data-dir tests test all
after_script:
- ./gantry undeploy all --force
- ./gantry status
