version: '3.0'

services:  
  vr-sros:
    image: ${DOCKER_REGISTRY_FQDN}/nlnetlabs/vr-sros:${DOCKER_TAG}
    network_mode: host
    privileged: true
    command: --username ${ROUTER_USER} --password ${ROUTER_PASS} --num-nics 1

  vr-csr:
    image: ${DOCKER_REGISTRY_FQDN}/vrnetlab/vr-csr:${DOCKER_TAG}
    network_mode: host
    privileged: true
    command: --username ${ROUTER_USER} --password ${ROUTER_PASS}

  vr-vmx:
    image: ${DOCKER_REGISTRY_FQDN}/vrnetlab/vr-vmx:${DOCKER_TAG}
    network_mode: host
    privileged: true
    command: --username ${ROUTER_USER} --password ${ROUTER_PASS}

  vr-xrv9k:
    image: ${DOCKER_REGISTRY_FQDN}/vrnetlab/vr-xrv9k:${DOCKER_TAG}
    network_mode: host
    privileged: true
    command: --username ${ROUTER_USER} --password ${ROUTER_PASS}

  routinator:
    image: nlnetlabs/routinator:latest
    network_mode: host
    ports:
      - "${ROUTINATOR_PORT}:${ROUTINATOR_PORT}"
    volumes:
      - /etc/routinator/tals/arin-rfc7730.tal:/root/.rpki-cache/tals/arin.tal

  testrunner:
    build: .