#!/bin/bash
GANTRY_BIND_MOUNT_HOST_DIR=/tmp/gantry
GANTRY_BIND_MOUNT_GUEST_DIR=/tmp/gantry
COMMON_ARGS="-it -e DEBUG -e ANSIBLE_DEBUG -e GANTRY_BIND_MOUNT_HOST_DIR=${GANTRY_BIND_MOUNT_HOST_DIR} -e GANTRY_BIND_MOUNT_GUEST_DIR=${GANTRY_BIND_MOUNT_GUEST_DIR}"
MANUAL_MODE=0

[[ $# -eq 1 && "$1" == "manual" ]] && MANUAL_MODE=1 && shift

docker container inspect gantry &>/dev/null
if [ $? -eq 0 ]; then
    echo "Connecting to existing instance of gantry.."
    echo
    CMD="/opt/nlnetlabs/gantry/cli"
    [ "${MANUAL_MODE}" -eq 1 ] && CMD=/bin/bash
    docker exec ${COMMON_ARGS} gantry ${CMD} $*
else
    ENTRYPOINT_OVERRIDE=""
    EXTRA_ARGS=""
    if [ "${MANUAL_MODE}" -eq 1 ]; then
        ENTRYPOINT_OVERRIDE="--entrypoint=/bin/bash"
        while [ $# -gt 0 ]; do shift; done
        echo 'Entering manual mode, have a nice day!'
        echo
    fi
    docker run ${COMMON_ARGS} ${ENTRYPOINT_OVERRIDE} \
        --name gantry \
        --env-file gantry.cfg \
        --volume gantry:/root/.docker/machine \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume ${GANTRY_BIND_MOUNT_HOST_DIR}:${GANTRY_BIND_MOUNT_GUEST_DIR}:ro \
        --rm \
        nlnetlabs/gantry:latest \
        $*
fi
