#!/bin/bash
GANTRY_IMAGE=nlnetlabs/gantry:latest
GANTRY_BIND_MOUNT_HOST_DIR=/tmp/gantry
GANTRY_BIND_MOUNT_GUEST_DIR=/tmp/gantry

ALREADY_RUNNING=0
docker container inspect gantry &>/dev/null && ALREADY_RUNNING=1

case $1 in
    upgrade)
        docker pull ${GANTRY_IMAGE} && shift
        exit 0
        ;;

    --data-dir)
        if [[ $# -ge 2 || ! -d "${GANTRY_BIND_MOUNT_HOST_DIR}" ]]; then
            if [ ${ALREADY_RUNNING} -eq 1 ]; then
                echo >&2 "ERROR: --data-dir cannot be changed when Gantry is already running..."
                exit 1
            fi
            GANTRY_BIND_MOUNT_HOST_DIR="$(realpath $2)" && shift 2
            echo "Data directory to use on host: ${GANTRY_BIND_MOUNT_HOST_DIR}"
        else
            set -- --help
        fi
        ;;
esac

COMMON_ARGS="-it -e DEBUG -e ANSIBLE_DEBUG -e GANTRY_BIND_MOUNT_HOST_DIR=${GANTRY_BIND_MOUNT_HOST_DIR} -e GANTRY_BIND_MOUNT_GUEST_DIR=${GANTRY_BIND_MOUNT_GUEST_DIR}"

if [ ${ALREADY_RUNNING} -eq 1 ]; then
    echo "Connecting to existing instance of gantry.."
    echo
    docker exec ${COMMON_ARGS} gantry /opt/nlnetlabs/gantry/cli $*
else
    docker run ${COMMON_ARGS} \
        --name gantry \
        --env-file gantry.cfg \
        --volume gantry:/root/.docker/machine \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume ${GANTRY_BIND_MOUNT_HOST_DIR}:${GANTRY_BIND_MOUNT_GUEST_DIR}:ro \
        --rm \
        ${GANTRY_IMAGE} \
        $*
fi