# VENDOR=NLnet Labs
# DROPLET_SIZE=s-1vcpu-1gb
- any_errors_fatal: yes
  hosts: rpkicaches
  tasks:
  - block:
    - name: "INSTALL PYTHON FOR ANSIBLE"
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: result
      changed_when: result.stdout != ""

    - name: "CREATE THE TALS DIRECTORY"
      file:
        path: /etc/routinator/tals
        state: directory

    - name: "DOWNLOAD THE TAL FILE"
      get_url:
        url: https://www.arin.net/resources/manage/rpki/arin-rfc7730.tal
        dest: /etc/routinator/tals/arin-rfc7730.tal

    - name: "CHECK TAL FILE EXISTS"
      stat:
        path: /etc/routinator/tals/arin-rfc7730.tal
      register: result
      failed_when: result.stat.exists == False

    - name: "CREATE ROUTINATOR CONFIG FILE"
      copy:
        dest: /root/.routinator.conf
        content: |
          repository-dir = "/tmp"
          tal-dir = "/root/.rpki-cache/tals/"
          log-level = "info"
          log = "stderr"
          listen-http = ["0.0.0.0:9556"]
          refresh = 60

  - block:
    - name: "RUN THE ROUTINATOR DOCKER CONTAINER ON THE ROUTINATOR HOST DOCKER DAEMON"
      register: result
      docker_container:
        name: routinator
        image: nlnetlabs/routinator:latest
        network_mode: host
        ports:
          - "{{ routinator_port }}:{{ routinator_port }}"
          - 9556:9556
        volumes:
          - /etc/routinator/tals/arin-rfc7730.tal:/root/.rpki-cache/tals/arin.tal
          - /root/.routinator.conf:/root/.routinator.conf

    - name: "CHECK THAT THE ROUTINATOR IS DEPLOYED"
      assert: { that: "result.ansible_facts.docker_container.State.Running" }

    - name: "WAIT FOR ROUTINATOR TO START LISTENING FOR CONNECTIONS"
      wait_for:
        host: "{{ hostvars['routinator'].ansible_host }}"
        port: "{{ routinator_port }}"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 600           # Stop checking after timeout (sec)
    connection: local
    environment:
      DOCKER_CERT_PATH: "{{ hostvars['routinator'].dm_DOCKER_CERT_PATH }}"
      DOCKER_HOST: "{{ hostvars['routinator'].dm_DOCKER_HOST }}"
      DOCKER_MACHINE_NAME: "{{ hostvars['routinator'].dm_DOCKER_MACHINE_NAME }}"
      DOCKER_TLS_VERIFY: "{{ hostvars['routinator'].dm_DOCKER_TLS_VERIFY }}"