---
- block:
  - name: "Include user defined config-*.yml tasks"
    include_tasks: "{{ item }}"
    with_fileglob:
      - "{{ user_task_fileglob }}"

  when: hostvars[inventory_hostname].dm_tags.find(component_name) != -1
  vars:
    user_task_fileglob: "{{ lookup('env', 'GANTRY_BIND_MOUNT_GUEST_DIR') }}/config-*.yml"